import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Layout, Text, Header, SectionHeading } from "../components/index";
import { motion } from "framer-motion";
import { Easing } from "../constants/index";

const Home: NextPage = () => {
  //const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <main className="pb-44">
          <SectionHeading
            caption="Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, earum aut iste, excepturi sit neque, nemo fugiat dolorum hic nesciunt magnam. Pariatur repellendus sint accusantium nemo voluptas et aperiam autem."
            title="Our Products"
          />
        </main>
      </Layout>
    </>
  );
};

export default Home;
