import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import {
  Layout,
  Header,
  SectionHeading,
  Products,
  CtaSectionBtn,
} from "../components/index";
import { Parallax, ParallaxLayer } from "@react-spring/parallax";

const Home: NextPage = () => {
  //const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <main className="pb-44">
          <section>
            <SectionHeading
              caption="Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, earum aut iste, excepturi sit neque, nemo fugiat dolorum hic nesciunt magnam. Pariatur repellendus sint accusantium nemo voluptas et aperiam autem."
              title="newest Products"
            />
            <Products
              products={[
                {
                  title: "Salmon",
                  caption:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                  tags: [{ id: "1", title: "Fish" }],
                },
                {
                  title: "Salmon",
                  caption:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                  tags: [{ id: "1", title: "Fish" }],
                },
                {
                  title: "Salmon",
                  caption:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                  tags: [{ id: "1", title: "Fish" }],
                },
                {
                  title: "Salmon",
                  caption:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                  tags: [{ id: "1", title: "Fish" }],
                },
                {
                  title: "Salmon",
                  caption:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                  tags: [{ id: "1", title: "Fish" }],
                },
                {
                  title: "Salmon",
                  caption:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                  tags: [{ id: "1", title: "Fish" }],
                },
              ]}
            />
            <CtaSectionBtn title="More Products" link="/products" />
          </section>
          <section className="relative">
            <SectionHeading
              caption="Lorem Ipsum dolor sit amet consecttu eut ejheut e shehtufjhe djfdtehe."
              title="The Ambience"
            />
          </section>
        </main>
      </Layout>
    </>
  );
};

export default Home;
