import type { NextPage } from "next";
import Head from "next/head";

import {
  Layout,
  Header,
  SectionHeading,
  Products,
  CtaSectionBtn,
  Ambience,
  EventType,
  Carousel,
} from "../components/index";
import Image from "next/image";

import { FrameProvider } from "framed-scroll-motion";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  //const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Gravitybar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrameProvider>
        <Layout>
          <Header />
          <main className="pb-44">
            <section>
              <SectionHeading
                caption="Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, earum aut iste, excepturi sit neque, nemo fugiat dolorum hic nesciunt magnam. Pariatur repellendus sint accusantium nemo voluptas et aperiam autem."
                title="newest Products"
              />
              <Products
                products={[
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    images: [{ id: "1", src: "/salmon.jpg" }],
                    type: "card",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "image",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "card",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "image",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "card",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "image",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "card",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "image",
                  },
                  {
                    title: "Salmon",
                    caption:
                      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo reiciendis ipsa temporibus quaerat sapiente placeat id. Quasi blanditiis quas delectus.",
                    tags: [{ id: "1", title: "Fish" }],
                    type: "card",
                  },
                ]}
              />
              <CtaSectionBtn title="More Products" link="/products" />
            </section>
            <section className="relative">
              <SectionHeading
                caption="Lorem Ipsum dolor sit amet consecttu eut ejheut e shehtufjhe djfdtehe."
                title="The Ambience"
              />
              <div className="grid grid-cols-1 sm:grid-cols-7 md:grid-cols-12 gap-24">
                <Ambience
                  imgSrc="/ambience-1.jpg"
                  className="sm:col-start-1 sm:col-end-6 md:col-start-2 md:col-end-6"
                />
                <Ambience
                  imgSrc="/ambience-2.jpg"
                  className="sm:col-start-2 sm:col-end-7 md:col-start-7 md:col-end-12 md:my-16"
                />
                <Ambience
                  imgSrc="/ambience-3.jpg"
                  className="sm:col-start-1 sm:col-end-6 md:col-start-2 md:col-end-7 md:my-32"
                />
                <Ambience
                  imgSrc="/ambience-3.jpg"
                  className="sm:col-start-1 sm:col-end-6 md:col-start-8 md:col-end-12 md:my-16"
                />
              </div>
              <div className="mt-24" />
              <EventType />
              <CtaSectionBtn title="Reservate" link="/reservate" />
            </section>
            <section>
              <SectionHeading
                caption="Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam repellat sint accusantium dolorem possimus, distinctio asperiores eligendi ab dolore impedit suscipit explicabo, et culpa officia obcaecati alias dolorum ut fugit voluptas quidem iusto tempora odit, aut eveniet! Molestiae consequuntur eveniet facere nam quibusdam animi adipisci nemo vitae provident porro! Atque!"
                title="About Us"
              />
              <div className="mt-24" />
              <h3 className="font-primary text-secondary-900 text-5xl text-center">
                Our Team
              </h3>
              <div className="mt-12" />
              <Carousel>
                <motion.div className="flex flex-row items-start">
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px] relative overflow-hidden">
                      <Image
                        src="/profile.png"
                        objectFit="cover"
                        layout="fill"
                        alt="Profile"
                      />
                    </div>
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                  <div className="flex flex-col items-start border-l border-secondary-900 p-6 space-y-6">
                    <span className="border border-secondary-900 text-secondary-900 px-4 py-2">
                      Cook
                    </span>
                    <div className="border border-secondary-900 rounded-md w-[200px] h-[200px]" />
                    <h4 className="font-primary text-3xl text-secondary-900">
                      Johnson Leyla
                    </h4>
                    <ul className="flex flex-row items-center">
                      <li className=""></li>
                      <li className=""></li>
                      <li className=""></li>
                    </ul>
                  </div>
                </motion.div>
              </Carousel>
            </section>
          </main>
        </Layout>
      </FrameProvider>
    </>
  );
};

export default Home;
