import type { NextPage } from "next";
import Head from "next/head";


const Reservate: NextPage = () => {
  //const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Gravitybar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main><h1>Reservate</h1></main>
    </>
  );
};

export default Reservate;
